### ISSUE TITLE
此插件与stone termux管理工具冲突

### ISSUE THREAD

**Issue by ghost** [2moe/tmoe-zsh#2]
![Screenshot_2021-05-13-19-58-17-62](https://user-images.githubusercontent.com/73503484/118125640-d8452100-b429-11eb-9d88-6e8baac14872.jpg)

**Comment by 2moe** [comment]
```shell
cd ${TMPDIR}
curl -Lo st https://gitee.com/st1020/Stone-Termux-Tool/raw/master/st.sh
chmod -v a+rx st
if [ -e ${PREFIX}/bin/st ]; then cp -vf ${PREFIX}/bin/st ./st.bak ; fi
mv -vf st ${PREFIX}/bin
```

**Comment by ghost** [comment]
还是不行
![Screenshot_2021-05-13-20-38-45-37](https://user-images.githubusercontent.com/73503484/118126721-4c33f900-b42b-11eb-8d6f-76ae9c2bc48f.jpg)

**Comment by 2moe** [comment]
你多打了空格

**Comment by ghost** [comment]
哪

**Comment by 2moe** [comment]
a+rx

**Comment by ghost** [comment]
st可以了，zsh-i又不行了
![Uploading Screenshot_2021-05-13-20-47-41-14.jpg…]()

**Comment by ghost** [comment]
![Screenshot_2021-05-13-20-47-41-14](https://user-images.githubusercontent.com/73503484/118127790-b39e7880-b42c-11eb-9229-128823667d97.jpg)

**Comment by 2moe** [comment]
```
bash -c "$(curl -L gitee.com/mo2/zsh/raw/2/2)"
```
选择第一项: 安装与配置

**Comment by ghost** [comment]
可以了谢谢
