### ISSUE TITLE
提个小bug

### ISSUE THREAD

**Issue by ghost** [2moe/tmoe-zsh#3]
![8c103b85a2dd4c2028bceed35a777d3d](https://user-images.githubusercontent.com/73503484/125391453-213c3600-e3d7-11eb-947f-1c5222df7a0b.jpg)
就是输入r后，息屏，然后在输m就成这样了

**Comment by 2moe** [comment]
termux版本号是多少？
安卓还是鸿蒙？哪个版本？
系统有没有限制termux后台运行？
___
抱歉，我这边并没有复现这个bug。

**Comment by 2moe** [comment]
可以做个小测试。
在termux上开ssh服务，然后使用其它终端/ssh客户端(例如juicessh)连接上termux, 最后测试一下熄屏后的表现。
```shell
pkg i -y openssh
#安装openssh-server

passwd
#修改密码

sshd
#启动ssh服务
```
默认端口 **8022** ,本机地址 **localhost**

**Comment by ghost** [comment]
额，0.116，安卓系统，抱歉，目前手边没有电脑，所以，装了ssh也没用
